
set -g @ctp_bg "#1e1e2e"
set -g @ctp_surface_1 "#45475a"
set -g @ctp_fg "#f5e0dc"
set -g @ctp_mauve "#c6a0f6"
set -g @ctp_crust "#11111b"
set -gF status-style "bg=#{@ctp_bg},fg=#{@ctp_fg}"
set -gF window-status-format "#[bg=#{@ctp_surface_1},fg=#{@ctp_fg}] ##I "
set -gF window-status-current-format "#[bg=#{@ctp_mauve},fg=#{@ctp_crust}] ##I "
set -g status-left ""
set -g status-right ""

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100

set -g mouse on
set -sg escape-time 0
set -g history-limit 50000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g default-terminal "tmux-256color"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind c new-window -c "#{pane_current_path}"

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

